import fs from 'fs'
import zlib from 'zlib'
const workbookPath = 'C:/Users/Administrator/Desktop/推广计划表.xlsx'
function readZipEntries(buffer) { let eocd=-1; for(let i=buffer.length-22;i>=0;i--){if(buffer.readUInt32LE(i)===0x06054b50){eocd=i;break}} const total=buffer.readUInt16LE(eocd+10), cdOffset=buffer.readUInt32LE(eocd+16); const entries=new Map(); let ptr=cdOffset; for(let i=0;i<total;i++){const method=buffer.readUInt16LE(ptr+10), compressedSize=buffer.readUInt32LE(ptr+20), fileNameLength=buffer.readUInt16LE(ptr+28), extraLength=buffer.readUInt16LE(ptr+30), commentLength=buffer.readUInt16LE(ptr+32), localOffset=buffer.readUInt32LE(ptr+42); const name=buffer.slice(ptr+46,ptr+46+fileNameLength).toString('utf8'); const localNameLength=buffer.readUInt16LE(localOffset+26), localExtraLength=buffer.readUInt16LE(localOffset+28); const dataStart=localOffset+30+localNameLength+localExtraLength; const compressed=buffer.slice(dataStart,dataStart+compressedSize); entries.set(name,(method===8?zlib.inflateRawSync(compressed):compressed).toString('utf8')); ptr+=46+fileNameLength+extraLength+commentLength} return entries }
function decodeXml(s=''){return s.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&apos;/g,"'")}
function parseAttrs(tag){const attrs={}; const re=/([A-Za-z_:][\w:.-]*)="([^"]*)"/g; let m; while((m=re.exec(tag))) attrs[m[1]]=decodeXml(m[2]); return attrs}
function stripTags(s=''){return decodeXml(s.replace(/<[^>]+>/g,''))}
function parseSharedStrings(xml=''){const values=[]; const siRe=/<si[\s\S]*?<\/si>/g; let m; while((m=siRe.exec(xml))){const texts=[]; const tRe=/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g; let t; while((t=tRe.exec(m[0]))) texts.push(decodeXml(t[1])); values.push(texts.join('')||stripTags(m[0]))} return values}
function parseWorkbook(entries){const workbook=entries.get('xl/workbook.xml')||'', rels=entries.get('xl/_rels/workbook.xml.rels')||''; const relMap=new Map(); let rel; const relRe=/<Relationship\b[^>]*>/g; while((rel=relRe.exec(rels))){const a=parseAttrs(rel[0]); relMap.set(a.Id,a.Target)} const sheets=[]; let sh; const sheetRe=/<sheet\b[^>]*>/g; while((sh=sheetRe.exec(workbook))){const a=parseAttrs(sh[0]); const t=relMap.get(a['r:id']); sheets.push({name:a.name,path:`xl/${t.replace(/^\//,'')}`.replace('xl/xl/','xl/')})} return sheets}
function colToIndex(ref){const letters=ref.replace(/[^A-Z]/g,''); let n=0; for(const ch of letters)n=n*26+(ch.charCodeAt(0)-64); return n-1}
function parseSheet(xml, ss){const rows=[]; let rowMatch; const rowRe=/<row\b[^>]*>[\s\S]*?<\/row>/g; while((rowMatch=rowRe.exec(xml))){const rowXml=rowMatch[0]; const rowAttrs=parseAttrs(rowXml.match(/<row\b[^>]*>/)?.[0]||''); const row=[]; const present=[]; let cellMatch; const cellRe=/<c\b[^>]*>[\s\S]*?<\/c>/g; while((cellMatch=cellRe.exec(rowXml))){const cellXml=cellMatch[0], attrs=parseAttrs(cellXml.match(/<c\b[^>]*>/)?.[0]||''); const idx=attrs.r?colToIndex(attrs.r):row.length; const v=cellXml.match(/<v>([\s\S]*?)<\/v>/); const inline=cellXml.match(/<is>([\s\S]*?)<\/is>/); let value=''; if(attrs.t==='s'&&v)value=ss[Number(v[1])]??''; else if(attrs.t==='inlineStr'&&inline)value=stripTags(inline[1]); else if(v)value=decodeXml(v[1]); row[idx]=String(value).trim(); present[idx]=true} if(row.some(Boolean)) rows.push({rowNum:Number(rowAttrs.r||rows.length+1),values:row,present})} return rows}
const entries=readZipEntries(fs.readFileSync(workbookPath)); const ss=parseSharedStrings(entries.get('xl/sharedStrings.xml')||''); const sheets=parseWorkbook(entries); for(const sheet of sheets){const xml=entries.get(sheet.path)||''; const rows=parseSheet(xml,ss); console.log('\nSHEET',sheet.name,'rows',rows.length); console.log('MERGES', (xml.match(/<mergeCell ref="[^"]+"/g)||[]).slice(0,30).map(x=>x.match(/ref="([^"]+)/)[1])); for(const r of rows.slice(0,35)){console.log(r.rowNum, JSON.stringify(r.values.slice(0,16)))} }
